version: '3.7'

services:

  database:
    container_name: database
    image: mysql
    restart: always
    environment:
      - MYSQL_USER=loans
      - MYSQL_PASSWORD=loans
      - MYSQL_DATABASE=test_task_skb
      - MYSQL_ROOT_PASSWORD=GH56sd234%

  backend:
    container_name: backend
    environment:
      - DATABASE_URL=jdbc:mysql://database:3306/test_task_skb?serverTimezone=UTC
    build:
      ./backend
    ports:
      - 8080:8080
    depends_on:
      - database